USE [master]
GO

/****** Object:  Database [DemoApiDb]    Script Date: 1/9/2020 3:16:41 PM ******/
CREATE DATABASE [DemoApiDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DemoApiDb', FILENAME = N'D:\SQL\SQL2014DEV\Data\DemoApiDb.mdf' , SIZE = 3264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DemoApiDb_log', FILENAME = N'D:\SQL\SQL2014DEV\Data\DemoApiDb_log.ldf' , SIZE = 816KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DemoApiDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DemoApiDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DemoApiDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DemoApiDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DemoApiDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DemoApiDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [DemoApiDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DemoApiDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DemoApiDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DemoApiDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DemoApiDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DemoApiDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DemoApiDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DemoApiDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DemoApiDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DemoApiDb] SET  ENABLE_BROKER 
GO

ALTER DATABASE [DemoApiDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DemoApiDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DemoApiDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DemoApiDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DemoApiDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DemoApiDb] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [DemoApiDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DemoApiDb] SET RECOVERY FULL 
GO

ALTER DATABASE [DemoApiDb] SET  MULTI_USER 
GO

ALTER DATABASE [DemoApiDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DemoApiDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DemoApiDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DemoApiDb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DemoApiDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DemoApiDb] SET  READ_WRITE 
GO


